### PR TITLE
Translate documents into Arabic

### PR DESCRIPTION
**Pull request by MesterPerfect**
I have translated documents into Arabic and I am working on translating addition phrases into Arabic as well

### CODE REVIEW

**Comment by Anirudha-JN** [comment]
I would like to work on this issue, please assign me this issue

**Comment by MesterPerfect** [comment]
> I would like to work on this issue, please assign me this issue

What is issue you want to work on

**Comment by Anirudha-JN** [comment]
the translation issue

**Comment by MesterPerfect** [comment]
I translated phrases and I Open pull
It remains only to be approved by @ruifontes
What do you want to work on?

**Comment by ruifontes** [comment]
Merged and closed.

**Pull request merged**
